services:
  email-send-rest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:6-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local  