services:
  email-send-rest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker


  redis:
    image: "redis:6-alpine"
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery-worker
    container_name: celery_worker
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - redis
